services:
  sshbin:
    container_name: sshbin
    image: sshbin/app
    build:
      context: .
      dockerfile: ./docker/sshbin/Dockerfile
      
    env_file: .env
    volumes:
      - sshbin-data:/data
  caddy:
    container_name: sshbin-caddy
    image: sshbin/caddy
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    env_file: .env
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "127.0.0.1:2019:2019/tcp"
      - "2022:2022/tcp"
      - "443:443/tcp"
      - "443:443/udp"
volumes:
  sshbin-data:
